version: 1

# Here we are defining all the services that are available in the system.
# A service is two topics in Kafka. One for requests and one for responses.

# The post processor will add the schema id and name
#   the name is the name of the schema in a way that the schema registry can find it
#   the id is the precise current value of the schema (based on the git hash)

where:
   services: "service/<service>/<reqOrResp>" # This is the naming convention. So if look at the first entry in capabilities services.equifax_creditCheck.request or services.equifax_creditCheck.response

services:

  "iorig-credit-bureau-uc-service":
    serviceDescription: "This interaction with UC, which provides credit history and affordability evaluations."
    request:
      topic: "iorig-credit-bureau-uc-service.request"
    response:
      topic: "iorig-credit-bureau-uc-service.response"

  iorig-aml-service:
    serviceDescription: "This is an internal service that evaluates the AML data and decides if the customer is a good risk"
    request:
      topic: "iorig-aml-service"
    response:
      topic: "iorig-aml-service"


#      uk.ipay.origination.aml.status.req
#      uk.ipay.origination.aml.status.res
#      se.loan.origination.aml.status.req
#      se.loan.origination.aml.status.res

