version: 1

parameters:
  product:
    legal:
      - instantLoan
      - mortgage
      - creditCard
      - carLoan
      - serviceLegal
  geo:
    legal:
      - uk
      - sw
      - ca
      - us
  channel:
    legal:
      - customerPortal
      - merchantPortal
      - selfServicePortal

services:
  experian_aml:
    description: "AML service provided by Experian for real-time background checks."
    request:
      topic: "experian.aml.request"
      schema: "https://schemas.mycompany.com/experian/aml/request/v1/amlRequest.avsc"
    response:
      topic: "experian.aml.response"
      schema: "https://schemas.mycompany.com/experian/aml/response/v1/amlResponse.avsc"

  equifax_creditCheck:
    description: "Credit score checking service provided by Equifax."
    request:
      topic: "equifax.creditScore.request"
      schema: "https://schemas.mycompany.com/equifax/creditScore/request/v2/creditScoreRequest.avsc"
    response:
      topic: "equifax.creditScore.response"
      schema: "https://schemas.mycompany.com/equifax/creditScore/response/v2/creditScoreResponse.avsc"

  experian_creditCheck:
    description: "Credit score checking service provided by Experian."
    request:
      topic: "experian.creditScore.request"
      schema: "https://schemas.mycompany.com/experian/creditScore/request/v2/creditScoreRequest.avsc"
    response:
      topic: "experian.creditScore.response"
      schema: "https://schemas.mycompany.com/experian/creditScore/response/v2/creditScoreResponse.avsc"

  internal_signatureVerification:
    description: "Internal signature verification service for document signing."
    request:
      topic: "internal.signatureVerification.request"
      schema: "https://schemas.mycompany.com/internal/signatureVerification/request/v1/signatureVerificationRequest.avsc"
    response:
      topic: "internal.signatureVerification.response"
      schema: "https://schemas.mycompany.com/internal/signatureVerification/response/v1/signatureVerificationResponse.avsc"

  internal_pricingService:
    description: "Internal pricing service for product and service pricing adjustments."
    request:
      topic: "internal.pricing.request"
      schema: "https://schemas.mycompany.com/internal/pricing/request/v3/pricingRequest.avsc"
    response:
      topic: "internal.pricing.response"
      schema: "https://schemas.mycompany.com/internal/pricing/response/v3/pricingResponse.avsc"

  internal_carloan_PricingService:
      description: "Internal pricing service for carloans"
      request:
        topic: "internal.pricing.request"
        schema: "https://schemas.mycompany.com/internal/pricing/request/v3/carloanspricingRequest.avsc"
      response:
        topic: "internal.pricing.response"
        schema: "https://schemas.mycompany.com/internal/pricing/response/v3/pricingResponse.avsc"

  internal_limitManagement:
    description: "Limit management service for transaction and account limits."
    request:
      topic: "internal.limitManagement.request"
      schema: "https://schemas.mycompany.com/internal/limitManagement/request/v1/limitManagementRequest.avsc"
    response:
      topic: "internal.limitManagement.response"
      schema: "https://schemas.mycompany.com/internal/limitManagement/response/v1/limitManagementResponse.avsc"
